CREATE TABLE rss (
    id BIGINT AUTO_INCREMENT NOT NULL,
    title VARCHAR(1000) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    uri VARCHAR(1000) NOT NULL,
    published_date TIMESTAMP WITH TIME ZONE,
    inserted_date TIMESTAMP WITH TIME ZONE NOT NULL
);
